CREATE TABLE "GCG_6252_LAST_DT_ISS"(
 "PART_NO" CHAR(17),
 "PART_REV" CHAR(3),
 "LOCATION" CHAR(2),
 "DATE_LAST_RUN" DATE DEFAULT NOW(),
 "TIME_LAST_RUN" CHAR(6) DEFAULT '000000',
 "LAST_USER" CHAR(8) );
